name: Build Android Testing APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Restore Keystore File
      run: |
        if [ -f "debug.keystore.base64" ]; then
          base64 -d debug.keystore.base64 > debug.keystore
          echo "Keystore restored from base64 file."
        else
          echo "Base64 file not found, creating a blank placeholder."
          touch debug.keystore
        fi

    - name: Build with Gradle
      run: |
        if [ -f "./gradlew" ]; then
          chmod +x ./gradlew
          ./gradlew assembleDebug
        elif [ -f "../gradlew" ]; then
          cd .. && chmod +x ./gradlew && ./gradlew assembleDebug
        else
          gradle assembleDebug
        fi
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Testing-APK
        path: |
          **/build/outputs/apk/debug/*.apk
